---
# Breaks reusing MD snippets extracted to files
first-line-heading: false

# Set maximum line Length to 140c to match Go linting
line-length:
  line_length: 140

# Allow HTML span elements to set font sizes and for shortcodes
# Allow <a id="short-heading"></a> to support [Link](#short-heading)
no-inline-html:
  allowed_elements:
    - a
    - code
    - div
    - li
    - p
    - span
    - ul

# Enforce our capitalisation rules (where they're unambiguous)
# Terms listed here should also be listed in the style guide in
# src/content/development/website/style-guide/_index.en.md
spelling:
  names:
    - Admiral
    - ClusterSet
    - Coastguard
    - Flannel
    - Globalnet
    - HTTP
    - IPsec
    - iptables
    - kind
    - Kubernetes
    - Lighthouse
    - OpenStack
    - Shipyard
    - subctl
    - Submariner
    - VXLAN
  code_blocks: false
