#!/bin/sh

set -ex

git checkout devel
make static
RELEASES=$(git for-each-ref --format='%(refname)' refs/remotes/origin | grep -E "origin/release-[0-9]+\.[0-9]+" | cut -d/ -f4)
for release in $RELEASES; do
    VERSION=${release#release-}
    git checkout $release
    make static OUTPUT_DIR="/${VERSION}/"
done
