#!/bin/sh

set -ex

git checkout devel
make static
RELEASES=$(git for-each-ref --format='%(refname)' refs/remotes/origin | awk -F/ '/release/ { print $NF }' )
for release in $RELEASES; do
    VERSION=${release#release-}
    git checkout $release
    make static OUTPUT_DIR="/${VERSION}/"
done
