#!/bin/sh
set -e -x

OUTPUT=/tmp/submariner-io.github.io

COMMIT_ID=$(git rev-parse --short HEAD)

rm -rf $OUTPUT 

git clone ssh://git@github.com/submariner-io/submariner-io.github.io $OUTPUT 

# prune old stuff (remove files which may go out)
rm -rf $OUTPUT/*

# copy new content
cp -rf output/* $OUTPUT

cd $OUTPUT
git add **
git commit -a -m "Updated website from submariner-io/website ${COMMIT_ID}"
git push
