---
name: Website

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Build the website static files
        run: make static-all

      - name: Upload proposed static website for review
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5
        with:
          name: Proposed static website
          path: output
